name: Release

on:
  push:
    branches: [master]

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: 生成 Changelog
        uses: jaywcjlove/changelog-generator@main
        id: changelog
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: 创建 Release
        uses: jaywcjlove/create-tag-action@main
        with:
          package-path: ./package.json
          release: true
          token: ${{ secrets.GITHUB_TOKEN }}
          body: |
            ${{ steps.changelog.outputs.compareurl }}

            ## 安装

            ```bash
            curl -sSL https://raw.githubusercontent.com/geek-fun/moli-skills/v${{ steps.changelog.outputs.version }}/install.sh | bash
            ```

            ## 更新内容

            ${{ steps.changelog.outputs.changelog }}
